// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createApiKey = `-- name: CreateApiKey :one

INSERT INTO coregateway.api_keys (
    key_prefix, key_hash, label, owner_user_id, scopes, expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, key_prefix, key_hash, label, owner_user_id, scopes, expires_at, revoked_at, last_used_at, created_at, updated_at
`

type CreateApiKeyParams struct {
	KeyPrefix   string             `json:"key_prefix"`
	KeyHash     string             `json:"key_hash"`
	Label       string             `json:"label"`
	OwnerUserID pgtype.UUID        `json:"owner_user_id"`
	Scopes      []string           `json:"scopes"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

// API keys (gateway-owned credentials for programmatic and service callers)
func (q *Queries) CreateApiKey(ctx context.Context, arg CreateApiKeyParams) (CoregatewayApiKey, error) {
	row := q.db.QueryRow(ctx, createApiKey,
		arg.KeyPrefix,
		arg.KeyHash,
		arg.Label,
		arg.OwnerUserID,
		arg.Scopes,
		arg.ExpiresAt,
	)
	var i CoregatewayApiKey
	err := row.Scan(
		&i.ID,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.Label,
		&i.OwnerUserID,
		&i.Scopes,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApiKeyByHash = `-- name: GetApiKeyByHash :one
SELECT id, key_prefix, key_hash, label, owner_user_id, scopes, expires_at, revoked_at, last_used_at, created_at, updated_at FROM coregateway.api_keys
WHERE key_hash = $1 LIMIT 1
`

func (q *Queries) GetApiKeyByHash(ctx context.Context, keyHash string) (CoregatewayApiKey, error) {
	row := q.db.QueryRow(ctx, getApiKeyByHash, keyHash)
	var i CoregatewayApiKey
	err := row.Scan(
		&i.ID,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.Label,
		&i.OwnerUserID,
		&i.Scopes,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listApiKeys = `-- name: ListApiKeys :many
SELECT id, key_prefix, label, owner_user_id, scopes, expires_at,
    revoked_at, last_used_at, created_at, updated_at
FROM coregateway.api_keys
ORDER BY created_at DESC
`

type ListApiKeysRow struct {
	ID          uuid.UUID          `json:"id"`
	KeyPrefix   string             `json:"key_prefix"`
	Label       string             `json:"label"`
	OwnerUserID pgtype.UUID        `json:"owner_user_id"`
	Scopes      []string           `json:"scopes"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListApiKeys(ctx context.Context) ([]ListApiKeysRow, error) {
	rows, err := q.db.Query(ctx, listApiKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApiKeysRow{}
	for rows.Next() {
		var i ListApiKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.KeyPrefix,
			&i.Label,
			&i.OwnerUserID,
			&i.Scopes,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeApiKey = `-- name: RevokeApiKey :execrows
UPDATE coregateway.api_keys
SET revoked_at = NOW(), updated_at = NOW()
WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeApiKey(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeApiKey, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchApiKeyLastUsed = `-- name: TouchApiKeyLastUsed :exec
UPDATE coregateway.api_keys
SET last_used_at = NOW()
WHERE id = $1
`

func (q *Queries) TouchApiKeyLastUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchApiKeyLastUsed, id)
	return err
}
