// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CoregatewayApiKey struct {
	ID          uuid.UUID          `json:"id"`
	KeyPrefix   string             `json:"key_prefix"`
	KeyHash     string             `json:"key_hash"`
	Label       string             `json:"label"`
	OwnerUserID pgtype.UUID        `json:"owner_user_id"`
	Scopes      []string           `json:"scopes"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type CoregatewayService struct {
	ID                  uuid.UUID        `json:"id"`
	Name                string           `json:"name"`
	Url                 string           `json:"url"`
	Icon                pgtype.Text      `json:"icon"`
	Description         pgtype.Text      `json:"description"`
	ServiceType         pgtype.Text      `json:"service_type"`
	HealthCheckInterval pgtype.Int4      `json:"health_check_interval"`
	HealthCheckMethod   pgtype.Text      `json:"health_check_method"`
	ExpectedStatusCodes []int32          `json:"expected_status_codes"`
	Timeout             pgtype.Int4      `json:"timeout"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
	IsActive            pgtype.Bool      `json:"is_active"`
}

type CoregatewayServiceHealthHistory struct {
	ID           uuid.UUID        `json:"id"`
	ServiceID    pgtype.UUID      `json:"service_id"`
	Status       string           `json:"status"`
	ResponseTime pgtype.Int4      `json:"response_time"`
	StatusCode   pgtype.Int4      `json:"status_code"`
	ErrorMessage pgtype.Text      `json:"error_message"`
	CheckedAt    pgtype.Timestamp `json:"checked_at"`
}

type CoregatewaySession struct {
	ID        uuid.UUID        `json:"id"`
	UserID    uuid.UUID        `json:"user_id"`
	TokenHash string           `json:"token_hash"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type CoregatewayUser struct {
	ID           uuid.UUID        `json:"id"`
	Email        string           `json:"email"`
	PasswordHash pgtype.Text      `json:"password_hash"`
	Role         string           `json:"role"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}
