// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountActiveSessions(ctx context.Context) (int64, error)
	CountAdmins(ctx context.Context) (int64, error)
	// API keys (gateway-owned credentials for programmatic and service callers)
	CreateApiKey(ctx context.Context, arg CreateApiKeyParams) (CoregatewayApiKey, error)
	CreateHealthHistory(ctx context.Context, arg CreateHealthHistoryParams) (CoregatewayServiceHealthHistory, error)
	CreateService(ctx context.Context, arg CreateServiceParams) (CoregatewayService, error)
	// Sessions
	CreateSession(ctx context.Context, arg CreateSessionParams) (CoregatewaySession, error)
	// Users
	CreateUser(ctx context.Context, arg CreateUserParams) (CoregatewayUser, error)
	DeleteExpiredSessions(ctx context.Context) error
	DeleteService(ctx context.Context, id uuid.UUID) error
	DeleteSession(ctx context.Context, id uuid.UUID) error
	DeleteSessionByTokenHash(ctx context.Context, tokenHash string) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	DeleteUserSessions(ctx context.Context, userID uuid.UUID) error
	GetAllServicesStats(ctx context.Context) (GetAllServicesStatsRow, error)
	GetApiKeyByHash(ctx context.Context, keyHash string) (CoregatewayApiKey, error)
	GetService(ctx context.Context, id uuid.UUID) (CoregatewayService, error)
	GetServiceHistory(ctx context.Context, arg GetServiceHistoryParams) ([]CoregatewayServiceHealthHistory, error)
	GetServiceStats24h(ctx context.Context, serviceID pgtype.UUID) (GetServiceStats24hRow, error)
	GetServiceStats30d(ctx context.Context, serviceID pgtype.UUID) (GetServiceStats30dRow, error)
	GetServiceStats7d(ctx context.Context, serviceID pgtype.UUID) (GetServiceStats7dRow, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash string) (GetSessionByTokenHashRow, error)
	GetUser(ctx context.Context, id uuid.UUID) (CoregatewayUser, error)
	GetUserByEmail(ctx context.Context, email string) (CoregatewayUser, error)
	ListActiveServicesForHealthCheck(ctx context.Context) ([]ListActiveServicesForHealthCheckRow, error)
	ListApiKeys(ctx context.Context) ([]ListApiKeysRow, error)
	ListServices(ctx context.Context) ([]ListServicesRow, error)
	ListUsers(ctx context.Context) ([]CoregatewayUser, error)
	RevokeApiKey(ctx context.Context, id uuid.UUID) (int64, error)
	TouchApiKeyLastUsed(ctx context.Context, id uuid.UUID) error
	UpdateService(ctx context.Context, arg UpdateServiceParams) (CoregatewayService, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (CoregatewayUser, error)
}

var _ Querier = (*Queries)(nil)
